### PR TITLE
servicenow_change_requests 0.2.0

### PR DESCRIPTION
**Pull request by kreeuwijk**
This PR:
- updates the puppetlabs/servicenow_change_requests module to 0.2.0
- updates the CD4PE custom deploy policy with the updated content from the module

### CODE REVIEW

**Review by timidri — COMMENTED** [review]
I can't really comment on the changes, but one question: what is the reason the deployment content is in the control repo as opposed to its own module?

**Comment by kreeuwijk** [comment]
Because CD4PE can only consume Custom Deployment Policies from the control repo. It doesn't support grabbing them from a module :-(

**Comment by timidri** [comment]
> Because CD4PE can only consume Custom Deployment Policies from the control repo. It doesn't support grabbing them from a module :-(

Does that apply to plans only, or also to functions?

**Review by stephenkpotter — APPROVED** [review]
LGTM

**Comment by kreeuwijk** [comment]
@timidri https://puppet.com/docs/continuous-delivery/4.x/custom_deployment_policy.html

**Comment by kreeuwijk** [comment]
Waiting for Dylan to update `onceover-codequality` gem so the dependency error gets resolved

**Pull request merged**
