### PR TITLE
replaced deprecated modules by their replacements

### PR DESCRIPTION
**Pull request by timidri**

### CODE REVIEW

**Comment by timidri** [comment]
Tests are currently failing because the [rgbank](https://github.com/ipcrm/puppetlabs-rgbank) module uses the deprecated `staging` module. Do we still want to keep the rgbank demo in our control repo? If so, we need to fork the module, replace the `staging` reference by `archive` and maintain it ourselves going forward. @reidmv @maju6406 what do you think?

**Comment by reidmv** [comment]
@timidri I would be ok with removing the rgbank demo entirely. Does anyone still use it?

**Comment by timidri** [comment]
Reconciled my previous Puppetfile updates with @reidmv 's latest ones, also replaced deprecated modules.
`puppet/staging` is deprecated but is used by the rgbank module, so I left that one in for the time being.

**Comment by stephenkpotter** [comment]
@timidri I think we agree we can get rid of rgbank at this point.

**Comment by timidri** [comment]
> @timidri I think we agree we can get rid of rgbank at this point.

Yep, we can do that in a later PR, the rest of the modules should be up to date now.
Maybe we should think about making upgrading an automated process since it's quite soul-crushing :-)

**Comment by stephenkpotter** [comment]
Duplicate to Reid's PR

**Comment by timidri** [comment]
@stephenkpotter @reidmv I don't think so: 
```
      "msg": "Errors while deploying environment 'master' (exit code: 1):\nERROR\t -> Environment \"updating-deprecated-modules\" contained non-word characters, ignoring it.\nWARN\t -> Puppet Forge module 'arioch-redis' has been deprecated, visit https://forge.puppet.com/arioch/redis for more information.\nWARN\t -> Puppet Forge module 'jonono-auditpol' has been deprecated, visit https://forge.puppet.com/jonono/auditpol for more information.\nWARN\t -> Puppet Forge module 'maestrodev-wget' has been deprecated, visit https://forge.puppet.com/maestrodev/wget for more information.\nWARN\t -> Puppet Forge module 'puppet-staging' has been deprecated, visit https://forge.puppet.com/puppet/staging for more information.\nWARN\t -> Puppet Forge module 'stankevich-python' has been deprecated, visit https://forge.puppet.com/stankevich/python for more information.\nERROR\t -> GitLab: The project you were looking for could not be found.\n at /opt/puppetlabs/server/data/code-manager/worker-caches/deploy-pool-2/git@gitlab.classroom.puppet.com-puppet-puppetlabs-ntp.git\n"
```

**Comment by timidri** [comment]
Reopening PR

**Pull request merged**
